# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.3"
manifest_format = "2.0"
project_hash = "5a9553361b70a1bc37f31fff6f0b47d79f21cd62"

[[deps.MarcIntegralArrays]]
git-tree-sha1 = "180e3b037c229d17a4aaa1d0de87fd11fd1e6f8f"
repo-rev = "master"
repo-url = "https://github.com/Marc-3d/MarcIntegralArrays.git"
uuid = "22adcb8d-38e9-4bca-bde9-f028a915c79c"
version = "0.1.0"

[[deps.Unroll]]
git-tree-sha1 = "ffb72124bbdab5f11b66e56b119224c151b3b3eb"
uuid = "36e64239-2ab9-4580-84fb-56737a503d36"
version = "0.1.0"
